
language: c
compiler: gcc
sudo: required
dist: trusty

install:
    - uname -a
    - sudo dpkg --add-architecture i386
    - sudo rm /var/lib/apt/lists/* -vf
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake gcc-multilib libc6:i386 libgcc1:i386
    - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - bzip2 -d gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2
    - tar xfv gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar

script:
    - export PATH=$PWD/gcc-arm-none-eabi-4_9-2015q3/bin:$PATH
    - gcc --version
    - make generic
    - cd build_generic && make -j`nproc`
    - cd ..
    - arm-none-eabi-gcc --version
    - make cortex-m4
    - cd build_cortex-m4 && make -j`nproc`
    - cd ..

notifications:
    on_success: change
    on_failure: always
